### PR TITLE
Implement health checking for HelmBroker

### PR DESCRIPTION
**Pull request by polskikiel**
**Description**

Changes proposed in this pull request:

- Implemented the same way for checking the health status of helm-broker and helm-controller.

**Related issue(s)**

### CODE REVIEW

**Comment by jasiu001** [comment]
IMO for now `readiness` probe does not inform the controller is really ready, maybe dummy empty addon (without any repo) should be created, after checking its status we will be sure at least one reconcile was run so the controller is ready.

**Comment by piotrmiskiewicz** [comment]
let's create a task for better readiness probe in the controller and merge it as it is

**Comment by polskikiel** [comment]
I created an issue for it: https://github.com/kyma-project/helm-broker/issues/29

**Comment by piotrmiskiewicz** [comment]
please, change the image

**Pull request merged**
