### PR TITLE
Add go report card badge

### PR DESCRIPTION
**Pull request by derberg**
**Description**

Changes proposed in this pull request:

- Add go report card badge

### CODE REVIEW

**Comment by derberg** [comment]
@mszostok I've added another badge based on https://docs.sourcegraph.com/user/repository/badges
what do you think, does it make sense in case of Helm Broker, would anyone use it as a dependency?  I wonder where number 12 is coming from

**Comment by mszostok** [comment]
it looks ok-ish 

The HB gives you an option to use client-go in your code. Using that guy https://github.com/kyma-project/helm-broker/tree/master/pkg/client  you can create (Cluster)AddonsConfiguration dynamically in your code, which means that you can add new addon or even enable HB in some namespace.

e.g. we are using that in console-backend-service :)

**Comment by mszostok** [comment]
btw. IMO it will be also nice to present the test coverage badge. Personally I'm using the https://coveralls.io/ but also the kubernets/kubernetes-sigs org has that enabled. 

e.g. 
- https://github.com/kubernetes-sigs/go-open-service-broker-client
- https://github.com/kubernetes-sigs/external-dns
whole list: https://coveralls.io/github/kubernetes-sigs and https://coveralls.io/github/kubernetes

btw. since we want to present our report then I will add a task to enable the golangci-lint on our CI to ensure that we will not have any regression and stay at `A+` level

**Comment by derberg** [comment]
> about the numbers:
The HB gives you an option to use client-go in your code. Using that guy https://github.com/kyma-project/helm-broker/tree/master/pkg/client you can create (Cluster)AddonsConfiguration dynamically in your code, which means that you can add new addon or even enable HB in some namespace.

I hope that's documented somewhere :P

**Pull request merged**
